- name: Copy default host onto
  template: src=vhosts/default.conf.j2 dest=/etc/apache2/sites-available/{{ inventory_hostname }}.conf

- name: Enable Vhosts
  command: a2ensite {{ inventory_hostname }}.conf 

- name: Restart apache
  service: name=apache2 state=restarted

- name: Copy Default 
  template: src=apache.j2 dest=/etc/nginx/sites-available/apache.conf