#- name: Create Key Pair
#  ec2_key:
#    name: "{{ keypair }}"
#    region: "{{ aws_region }}"
#    key_material:  "{{ lookup('file',  ssh_key_location ) }}" 
#    #with_file: /home/pi/.ssh/nex.pem

#- name: Create a security group
#  local_action: 
#  module: 
#  ec2_group:
#  name: "{{ security_group }}"
#  description: Security Group for webserver Servers
#  region: "{{ region }}"
#  rules:
#        - proto: tcp
#          from_port: 22
#          to_port: 22
#          cidr_ip: 0.0.0.0/0
#        - proto: tcp
#          from_port: 80
#          to_port: 80
#          cidr_ip: 0.0.0.0/0

- name: Create an EC2 instance
  ec2:
    keypair: "{{ keypair }}"
#    keyname: "{{ keypair }}"
    region: "{{ aws_region }}"
#    group: "{{ security_group }}"
#    group_id: "{{ group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    instance_tags:
      Env: "{{ env }}"
      Name: "{{ project_name }}"
    count_tag:
      Env: "{{ env }}"
      Name: "{{ project_name }}"
    exact_count: "{{ instance_count }}"
  register: ec2

- name: Add new instances to host group
  add_host: hostname={{ item.public_dns_name }} groupname=launched
  with_items: "{{ ec2.instances }}"

- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  local_action: lineinfile
                dest="./hosts"
                regexp={{ item.public_ip }}
                insertafter={{ project_name }}  line="{{ item.public_ip }} ansible_user=ec2-user  ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=720 state=started
  with_items: "{{ ec2.instances }}"
